banch-name-validator.yml
updating the branch name validations

diff --git a/.github/workflows/brbanch-name-validator.yml b/.github/workflows/brbanch-name-validator.yml
--- a/.github/workflows/brbanch-name-validator.yml
+++ b/.github/workflows/brbanch-name-validator.yml
@@ -13,17 +13,13 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set script permissions
-        run: chmod +x ./.github/scripts/validate-branch-name.sh
-
-      - name: Get branch name
-        id: get_branch
-        run: |
-          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
-            BRANCH_NAME=${GITHUB_HEAD_REF}
-          else
-            BRANCH_NAME=${GITHUB_REF#refs/heads/}
-          fi
-
       - name: Validate Branch Name
-        run: ./.github/scripts/validate-branch-name.sh ${{ steps.get_branch.outputs.branch }}
+        run: |
+          if [[ ! "${{ github.head_ref }}" =~ ^(feature|release|hotfix)/.*$ ]]; then
+            echo "❌ Invalid branch name: ${{ github.head_ref }}"
+            echo "Branch names must start with 'feature/', 'release/', or 'hotfix/'." >&2
+            exit 1
+          else
+            echo "✅ Valid branch name: ${{ github.head_ref }}"
+          fi
+      
